-- Run this in Supabase SQL Editor (after your first schema.sql).
-- Adds: analytics tracking, and a storage bucket + policies for image uploads.

-- ---------- analytics ----------
create table if not exists page_views (
  id bigint generated by default as identity primary key,
  shop_id uuid references shops(id) on delete cascade not null,
  path text,
  referrer text,
  created_at timestamptz default now()
);

alter table page_views enable row level security;

-- Anyone visiting a public shop page can record a view.
create policy "Anyone can record a page view"
  on page_views for insert
  with check (true);

-- Only the shop's owner can read their own analytics.
create policy "Shop owners can read their own analytics"
  on page_views for select
  using (
    exists (
      select 1 from shops where shops.id = page_views.shop_id and shops.owner_id = auth.uid()
    )
  );

-- ---------- image uploads ----------
insert into storage.buckets (id, name, public)
values ('shop-images', 'shop-images', true)
on conflict (id) do nothing;

-- Each user can only upload into a folder named after their own user id
-- (the app uploads to `<user_id>/...`), so one user can't overwrite another's files.
create policy "Users can upload their own shop images"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'shop-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "Users can update their own shop images"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'shop-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
